src/main/java/com/cleanroommc/groovyscript/registry/VirtualizedRegistry.java
The `VirtualizedRegistry<R>` class allows for convenience storing and retrieving of recipes thanks to the `scripted` and `backup` collections. These collections would be in charge of storing script-generated recipes and saving existing recipes that have been deleted by scripts, respectively. For this purpose, the `addScripted` and `addBackup` methods are used whenever the script calls any of the mod compatibility recipe functions like `addRecipe(...)` or `removeRecipe(...)`. When reloading the script, recipes from the `scripted` collection would get purged from the mod, while recipes in the `backup` collection would be restored to the mod.
During testing, I happened to notice that adding and removing the same user-generated recipe through GroovyScript would cause both `addScripted` and …
=> Modifications to addBackup() behaviour

src/main/java/com/cleanroommc/groovyscript/core/mixin/InventoryCraftingAccess.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/OreDictionaryAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/SlotCraftingAccess.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/draconicevolution/FusionRegistryAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/ClassicCanningMachineRegistryAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/ElectrolyzerRecipeManagerAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/FermenterRecipeManagerAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/ScrapboxRecipeManagerAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/SemiFluidFuelManagerAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/thermalexpansion/BrewerManagerAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/thermalexpansion/CrucibleManagerAccessor.java
Fixes several warnings about no remapping targets when building the project, namely:
```
Note: Writing refmap to /home/alongstringofnumbers/IdeaProjects/GroovyScript/build/tmp/compileJava/compileJava-refmap.json
/home/alongstringofnumbers/IdeaProjects/GroovyScript/build/sources/main/java/com/cleanroommc/groovyscript/core/mixin/draconicevolution/FusionRegistryAccessor.java:13: warning: Unable to locate obfuscation mapping for @Accessor target REGISTRY
@Accessor
^
/home/alongstringofnumbers/IdeaProjects/GroovyScript/build/sources/main/java/com/cleanroommc/groovyscript/core/mixin/ic2/ScrapboxRecipeManagerAccessor.java:12: warning: Unable to locate obfuscation mapping for @Accessor target drops
@Accessor
^
/home/alongstringofnumbers/IdeaProjects/GroovyScript/build/sources/main/java/com/cleanro …
```
=> Fix several warnings about remapping mixins

src/main/java/com/cleanroommc/groovyscript/compat/vanilla/Crafting.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/Furnace.java, src/main/java/com/cleanroommc/groovyscript/helper/SimpleObjectStream.java
Adds more methods for recipe removal.
- SimpleObjectStream now has an implementation for `removeIf`
- Crafting and Furnace recipe removals can now optionally have their error logs disabled
- You can now get a stream of Crafting recipes
- You can now remove Crafting recipes based on their inputs
- You can now remove Furnace recipes based on their output
=> Additional Removal Options

build.gradle, examples/extremecrafting.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/api/IIngredient.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/bloodmagic/AlchemyTable.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/bloodmagic/BloodAltar.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/bloodmagic/TartaricForge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/CombinationCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/CompressionCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/EnderCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/EnderRecipeBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/ExtendedCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/ShapedTableRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/ShapelessTableRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/TableCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/extendedcrafting/TableRecipeBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/CraftingRecipeBuilder.java, src/main/java/com/cleanroommc/groovyscript/core/LateMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/extendedcrafting/ItemRecipeMakerMixin.java, src/main/java/com/cleanroommc/groovyscript/helper/ingredient/IngredientHelper.java, src/main/resources/mixin.groovyscript.extendedcrafting.json
what this PR adds:
- compat with Extended Crafting Compression crafting (crafttweaker level, consume catalyst)
- compat with Extended Crafting Combination crafting (crafttweaker level)
- compat with Extended Crafting Ender Crafting crafting (crafttweaker level, shapeless crafts, mirrored shaped crafts, key matrix)
- compat with Extended Crafting Table Crafting crafting (basic crafting, tier selection, shapeless/shaped/mirrored, key matrix)
- any of the above compats which have a config value for a default value respects that config
- a NonNullList conversion to IngredientHelper, and updated blood magic compat to use it
- an override in `IIngredient` for `withStack`
currently not implemented:
- recipe transformers for Ender Crafting (might not work regardless) and Table Crafting (part of …
=> Extended Crafting compat

build.gradle, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Apothecary.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Botania.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Brew.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/ElvenTrade.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Flowers.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Knowledge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Lexicon.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Magnet.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/ManaInfusion.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Orechid.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/OrechidIgnem.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/PureDaisy.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/RuneAltar.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/recipe/MagnetSubject.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/recipe/OrechidRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/recipe/PageChange.java, src/main/java/com/cleanroommc/groovyscript/core/LateMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/botania/BotaniaAPIAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/botania/PageCraftingRecipeMixin.java, src/main/resources/mixin.groovyscript.botania.json
Adds support for Botania.
Adds recipes additon/removal for:
- The Brewing Stand
- The Petal Apothecary
- The Rune Altar
- Elven Trade
- Mana Infusion
- The Pure Daisy
- The Orechid
- The OrechidIgnem
Adds support for adding/removing blocks and items from the magnet blacklist.
Adds convenience methods for registering custom flowers.
Adds support for adding custom brews.
Adds support for adding custom knowledge types.
Adds support for adding/removing lexicon categories.
Adds support for adding/removing lexicon entries.
Adds support for adding/removing lexicon pages.
=> Botania Support

src/main/java/com/cleanroommc/groovyscript/GroovyScript.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/LoaderControllerMixin.java
Runs the `POST_INIT` loader on `FMLLoadComplete` instead of `FMLPostInitialization`. (while making sure run before JEI loads)
This solves any issues with scripts being run before a mod loads required recipes or other things, including an existing issue where Tinkers' registers melting recipes after scripts are run.
Also added logs that say how long the first script loads took.
=> Run PostInit scripts on LoadComplete

src/main/java/com/cleanroommc/groovyscript/api/IIngredient.java, src/main/java/com/cleanroommc/groovyscript/brackets/BlockStateBracketHandler.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tcomplement/HighOven.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tcomplement/Melter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/Alloying.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/Casting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/Drying.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/Melting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/SmelteryFuel.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/FluidStackMixin.java, src/main/java/com/cleanroommc/groovyscript/helper/ingredient/IngredientHelper.java
- Add an `isEmpty()` method to `IIngredient` that can be overridden for ingredients that don't have any matching stacks. (Fixes `IngredientHelper.isEmpty()` always returning true for FluidStacks)
- Fixes the blockstate bracket handler causing a `ClassCastException` when using arguments.
- Changes `%s` to `{}` in the tinkers compat logs.
- Fixes some logic errors in the tinkers compat.
=> Minor Fixes

src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/JustEnoughItems.java
Allows you to yeet a ton of items at the same time via varargs, which is both more convenient and more performant.
=> Add a varargs variant for yeeting items in JEI

src/main/java/com/cleanroommc/groovyscript/core/GroovyScriptCore.java, src/main/java/com/cleanroommc/groovyscript/sandbox/ScriptModContainer.java
The run folder was being set as the source for the `ScriptModContainer::source`, which introduced the `.minecraft` folder as a classpath for the class loader.
AgriCraft uses the `org.reflections` library which compiles all the paths and searches resources through all of them, the source that GroovyScript puts in comes up first, leading to a relative path of `config/agricraft/json/defaults` when AgriCraft *always* expects it in its own jar which is just `json/defaults`, hence every time the path is being resolved, it appends `config/agricraft/` before it.
=> Fixes #84 + Fixes #110

src/main/java/com/cleanroommc/groovyscript/api/IScriptReloadable.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModPropertyContainer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/evilcraft/BloodInfuser.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/evilcraft/EnvironmentalAccumulator.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Forestry.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/integrateddynamics/DryingBasin.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/integrateddynamics/MechanicalDryingBasin.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/integrateddynamics/MechanicalSqueezer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/integrateddynamics/Squeezer.java, src/main/java/com/cleanroommc/groovyscript/registry/ReloadableRegistryManager.java
Forestry already had a similar system in place, but applied exclusively to its own compat and didn't provide any error logging.
Now individual registries can override the `isEnabled` method to ensure the registry actually exists. Only applied this to Integrated Dynamics (resolving #125), Blood Magic (uses same internals), and Forestry (pre-existing).
now, when loading into the world you will be presented with a much more helpful error message of "that registry is disabled" instead of just "Null Pointer Exception".
don't know what appends the `Possible solutions:` line, which in this context provides incorrect information.
=> Add isEnabled to IScriptReloadable, clarifying some NPE errors

dependencies.gradle, examples/postInit/betterwithmods.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/AnvilCrafting.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/AnvilRecipeBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/AnvilShapedRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/AnvilShapelessRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/BetterWithMods.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Cauldron.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Crucible.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Heat.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Hopper.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/HopperFilters.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Kiln.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/MillStone.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Saw.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/Turntable.java, src/main/java/com/cleanroommc/groovyscript/core/LateMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/betterwithmods/BWMHeatRegistryAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/betterwithmods/HopperFiltersAccessor.java, src/main/resources/assets/groovyscript/lang/en_us.lang, src/main/resources/mixin.groovyscript.betterwithmods.json
what this PR adds:
- compat with `anvilCrafting`, `cauldron`, `crucible`, `kiln`, `millStone`, `saw`, `turntable`, `heat`, `hopper`, and `hopperFilters`
- `anvilCrafting` has all the abilities of a normal crafting table (recipeFunction and recipeAction), which i believe adds novel functionality
- examples for the above
- i18n keys for the above
CraftTweaker, through ModTweaker, has the following explicit compat with Better With Mods that is _not_ added in this PR:
- `bellows`, controlling how far specific items are blown by the Bellows block
- `pulleymanager`, allows adding what blocks can be pulleys
- `buoyancy`, controlling if specific items float or sink in water
- `hcfurnace`, allows setting the time in ticks a given input smelting item takes (only active with the hardmode module …
=> add Better With Mods compat

dependencies.gradle, examples/postInit/alchemistry.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Alchemistry.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Atomizer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Combiner.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Dissolver.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Electrolyzer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Evaporator.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/alchemistry/Liquifier.java, src/main/resources/assets/groovyscript/lang/en_us.lang
what this PR adds:
- Adds compat for the `atomizer`, `combiner`, `dissolver`, `electrolyzer`, `evaporator`, `liquifier`.
- i18n wiki keys for the above
- examples file for the above
- `element` game object handler to get the alchemistry element or compound for the given name
something that is not added in this PR:
- crafttweaker, through native compat, adds Create Element and Create Compound helpers. these are not added in this PR. a TODO is added for these helpers.
note: when testing, i suggest also enabling Draconic Evolution for the Creative Power Source (no way to get power otherwise)
=> add Alchemistry compat

examples/postInit/jei.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Catalyst.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Category.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Description.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Ingredient.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/JeiPlugin.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/JustEnoughItems.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/jei/IngredientInfoRecipeAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/jei/ModRegistryAccessor.java, src/main/java/com/cleanroommc/groovyscript/registry/ReloadableRegistryManager.java, src/main/resources/assets/groovyscript/lang/en_us.lang, src/main/resources/mixin.groovyscript.jei.json
- added the ability to remove non-items and non-fluids from the ingredients side (requires the type of ingredient to be specified)
- adds the ability to remove all ingredients of a given type
- adds the ability to remove all ingredients :trollface: 
- adds the ability to add and remove catalyst items from categories
- adds the ability to remove all catalysts of a specific category
- adds the ability to add and remove JEI descriptions (a special tab in JEI which displays information related to an item)
- adds lang keys for the wiki and an examples file for the above
- methods formerly directly inside `JEI` are now inside subregistries, so eg `mods.jei.hide` must now be `mods.jei.ingredient.hide`
=> Better JEI compat

dependencies.gradle, examples/postInit/rustic.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/Alchemy.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/BrewingBarrel.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/CondenserRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/CrushingTub.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/EvaporatingBasin.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/ExtendedEvaporatingBasinRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/Rustic.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- Custom `ICondenserRecipe` and `IEvaporatingBasinRecipe` classes to allow additional customization of these recipes types.
- `ExtendedEvaporatingBasinRecipe` allows customizing the time taken.
- `CondenserRecipe` allows customizing fluid input, bottle slot item, and time taken.
- Adds `BrewingBarrel`, `CrushingTub`, `EvaporatingBasin`, and `Condenser` (both basic and advanced) compat
- adds examples file and i18n wiki keys for the above compat.
=> add Rustic compat

examples/postInit/pyrotech.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/astralsorcery/starlightaltar/AltarRecipeBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/betterwithmods/MillStone.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/Combiner.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/ElectrolyticSeparator.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/MetallurgicInfuser.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/PressurizedReactionChamber.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/Sawmill.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/pyrotech/ChoppingBlock.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/pyrotech/SoakingPot.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/Alchemy.java, src/main/java/com/cleanroommc/groovyscript/documentation/Builder.java, src/main/java/com/cleanroommc/groovyscript/documentation/Registry.java, src/main/java/com/cleanroommc/groovyscript/registry/AbstractCraftingRecipeBuilder.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- adds some more checks for missing document stuff, logging as warns.
- No methods targeting an annotated field (`Couldn't find any methods targeting field '{}' in recipe builder '{}'`)
- No such annotated field targeted by a method (`Couldn't find field '{}' referenced in a method used for recipe builder '{}'`)
- No fields used at all (`Couldn't find any fields being used for recipe builder '{}'`)
- removed an used constructor param for the `Builder`.
- updated annotations, a lang key, and an example file to ensure existing annotations pass these checks. (impacts `Pyrotech`, `Astral Sorcery`, `Mekanism`, and `Rustic`)
=> More validation of documenting annotations 

dependencies.gradle, examples/postInit/industrialforegoing.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/BioReactor.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/Extractor.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/FluidDictionary.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/IndustrialForegoing.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/LaserDrill.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/OreFermenter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/OreRaw.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/OreSieve.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/ProteinReactor.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/SludgeRefiner.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/industrialforegoing/Straw.java, src/main/java/com/cleanroommc/groovyscript/core/LateMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/industrialforegoing/SludgeRefinerBlockAccessor.java, src/main/resources/assets/groovyscript/lang/en_us.lang, src/main/resources/mixin.groovyscript.industrialforegoing.json
- adds `BioReactor`, `Extractor`, `FluidDictionary`, `LaserDrill`, `OreFermenter`, `OreRaw`, `OreSieve`, `ProteinReactor`, `SludgeRefiner`, and `Straw` compat.
- adds examples file and i18n wiki keys for the above compat.
=> add Industrial Foregoing compat

examples/postInit/immersiveengineering.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Crusher.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Excavator.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- adds methods to modify secondary outputs for the Immersive Engineering Crusher.
- updates examples and relevant i18n keys to support this change.
- converts the Immersive Engineering Excavator compat to use the same method to convert a `List<Float>` into `float[]`.
resolves #167
=> Immersive Engineering Crusher Recipe Secondary Output

src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Botania.java
- makes lexicon category/entry/page work again
- broken by this change: https://github.com/CleanroomMC/GroovyScript/commit/6b5a6591ad6f9ddbb0355e2fec39dfec10816e17#diff-b554e3ef8e3d9073eb8c44f7c67d3920a2f59310f091ca41237afddca77891e8
=> fix botania lexicon not being added

examples/postInit/roots.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/roots/FlowerGeneration.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- adds the `allowedSoils` feature for Flower Generation
- technically just uncomments it
- i18n key and example
=> add allowedSoils for Flower Generation

src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/ImmersiveEngineering.java
- make sure the input integer is equal to the ingredient amount for IE IngredientStack creation
resolves #190
=> Fix IE Oredict item count

src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/ArcFurnace.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Crusher.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Fermenter.java
- make sure the input `IIngredient` is converted into an IE `IngredientStack` for three IE compats that it was before. 
resolves #195
=> Fix some IE Recipe Builders not using IIngredient properly

src/main/java/com/cleanroommc/groovyscript/sandbox/GroovySandbox.java, src/main/java/com/cleanroommc/groovyscript/sandbox/GroovyScriptSandbox.java
This PR fixes edge cases where the running status of the GroovyScript sandbox is reported, falsely, as not running.
Reproduction Case:
```groovy
import gregtech.integration.groovy.GroovyScriptModule
import net.minecraft.item.ItemStack
println('Hello World!')
println(GroovyScriptModule.isCurrentlyRunning())
var test = { ItemStack stack ->
println("Hello World (2)! " + stack.toString())
}
test(item('minecraft:apple'))
println(GroovyScriptModule.isCurrentlyRunning())
```
This script uses GT just to report the status of the sandbox, but it should work without gt dependency. This was reproduced in an instance with just GroovyScript and its deps, + GT and its deps.
Output of running the above script:
```
[21:59:45] [SERVER/INFO] [groovyscript]: ========== Reloading Groovy scripts ========== …
```
=> Fix Edge Case Running Status of Sandbox

src/main/java/com/cleanroommc/groovyscript/core/mixin/ForgeRegistryMixin.java
This fixes a rare error when an entry is already present in the registry on reloading.
=> Fix "value already present" error on reloading

dependencies.gradle, examples/postInit/atum.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/atum/Atum.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/atum/Kiln.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/atum/Quern.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/atum/SpinningWheel.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- adds `Kiln`, `Quern`, and `SpinningWheel` compat.
- adds examples file and i18n wiki keys for the above compat.
does not add compat for the `KilnBlacklist`
=> add Atum 2 compat

dependencies.gradle, examples/postInit/primal_tech.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/primaltech/ClayKiln.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/primaltech/PrimalTech.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/primaltech/StoneAnvil.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/primaltech/WaterSaw.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/primaltech/WoodenBasin.java, src/main/java/com/cleanroommc/groovyscript/core/LateMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/primal_tech/ClayKilnRecipesAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/primal_tech/StoneAnvilRecipesAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/primal_tech/WaterSawRecipesAccessor.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/primal_tech/WoodenBasinRecipesAccessor.java, src/main/resources/assets/groovyscript/lang/en_us.lang, src/main/resources/mixin.groovyscript.primal_tech.json
- adds`ClayKiln`, `StoneAnvil`, `WaterSaw`, and `WoodenBasin` compat.
- adds examples file and i18n wiki keys for the above compat.
- use a mixin for each compat, as init method is private
=> add Primal Tech compat

examples/postInit/aether_legacy.groovy, examples/postInit/atum.groovy, examples/postInit/botania.groovy, examples/postInit/botanicadds.groovy, examples/postInit/cyclicmagic.groovy, examples/postInit/extrabotany.groovy, examples/postInit/mekanism.groovy, examples/postInit/mysticalagriculture.groovy, examples/postInit/primal_tech.groovy, examples/postInit/projecte.groovy, examples/postInit/roots.groovy, examples/postInit/theaurorian.groovy, src/main/java/com/cleanroommc/groovyscript/documentation/Documentation.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- fix punctuation being matched against exclusively period to determine if a period is added, instead of `./!/?`, which currently leads to a few situations of `!.` at the end of a paragraph.
- rename the second instance of Aether Legacy Freezer to Freezer Fuel.
- fix Pyrotech's Kiln having an empty lang key and having a typo'd correct lang key.
- update examples with the new docs.
noticed these while creating this PR: https://github.com/CleanroomMC/cleanroom-website/pull/18
=> fix multiple punctuation marks

src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Category.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/prodigytech/ExplosionFurnaceAdditives.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/prodigytech/ZorraAltar.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/Coolant.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/Diffuser.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/Fisher.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/FisherBait.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/Tapper.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/TapperFertilizer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/TapperTree.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/device/XpCollector.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Compression.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Enervation.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Lapidary.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Magmatic.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Numismatic.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/dynamo/Steam.java
This PR converts all usages of Records in GroovyScript to use Classes instead, preserving the same functions as before.
This is because these records were not compiled correctly, causing occasional GrS errors on some machines in some environments.
=> Convert all Records to Classes

src/main/java/com/cleanroommc/groovyscript/sandbox/RunConfig.java
This PR properly resolves Symbolic Links when searching through the `groovy` folder to find scripts. This means that sub folders and individual files of the `groovy` folder can now be symlinked (`postInit` folder or folders inside `postInit`, etc.), rather than having the whole `groovy` folder required to be symlinked beforehand.
This results in potential improvements for developers.
This might introduce cases where recursive symlinks cause an infinite walk, which could be controlled with a limit on directory search, but given the rarity of such a case, and potential issues directory search limits could introduce, this has not been directly added in this PR.
=> Resolve Symbolic Links in Groovy Folder in Debug Mode

src/main/java/com/cleanroommc/groovyscript/core/visitors/InvokerHelperVisitor.java
The current `InvokerHelperVisitor` does not transfrom the frame, this pr fixes this problem.
This pr manually processes the frame. Of course, it can also be changed to automatic (`ClassWriter#COMPUTE_FRAMES`)
```
// Why did you do that?
Time: 8/19/24 9:41 PM
Description: Initializing game
java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
Location:
org/codehaus/groovy/runtime/InvokerHelper.createMap([Ljava/lang/Object;)Ljava/util/Map; @20: iload_2
Reason:
Type 'it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap' (current frame, locals[1]) is not assignable to 'java/util/LinkedHashMap' (stack map, locals[1])
Current Frame:
bci: @20
flags: { }
locals: { '[Ljava/lang/Object;', 'it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap', integer, …
```
=> InvokerHelperVisitor visit the frame

src/main/java/com/cleanroommc/groovyscript/sandbox/security/GroovySecurityManager.java
- remove the package `com.cleanroommc.groovyscript.registry` from the blacklist
`DummyRecipe` cannot be blacklisted to properly iterate through recipes, and the other classes are just registry classes/wrappers. dont see anything in there that requires being blocked and having it be accessible makes adding things like custom reloadable compat much easier.
=> Unblacklist GrS registry

editors/vscode/package-lock.json, editors/vscode/package.json, editors/vscode/src/features/TextureDecoration.ts, editors/vscode/src/languageProviders/TextureDecorationLanguageProvider.ts, editors/vscode/src/main.ts, src/main/java/com/cleanroommc/groovyscript/GroovyScript.java, src/main/java/com/cleanroommc/groovyscript/gameobjects/GameObjectHandlerManager.java, src/main/java/com/cleanroommc/groovyscript/mapper/ObjectMapper.java, src/main/java/com/cleanroommc/groovyscript/mapper/ObjectMapperManager.java, src/main/java/com/cleanroommc/groovyscript/mapper/TextureBinder.java, src/main/java/com/cleanroommc/groovyscript/server/GroovyScriptCapabilities.java, src/main/java/com/cleanroommc/groovyscript/server/GroovyScriptFeaturesService.java, src/main/java/com/cleanroommc/groovyscript/server/GroovyScriptLanguageServer.java, src/main/java/com/cleanroommc/groovyscript/server/GroovyScriptLanguageServerImpl.java, src/main/java/com/cleanroommc/groovyscript/server/GroovyScriptServices.java, src/main/java/com/cleanroommc/groovyscript/server/features/textureDecoration/TextureDecorationInformation.java, src/main/java/com/cleanroommc/groovyscript/server/features/textureDecoration/TextureDecorationParams.java, src/main/java/com/cleanroommc/groovyscript/server/features/textureDecoration/TextureDecorationProvider.java, src/main/java/net/prominic/groovyls/GroovyLanguageServer.java, src/main/java/net/prominic/groovyls/GroovyServices.java, src/main/java/net/prominic/groovyls/compiler/util/GroovyASTUtils.java, src/main/java/net/prominic/groovyls/providers/CompletionProvider.java, src/main/java/net/prominic/groovyls/providers/DocProvider.java, src/main/java/net/prominic/groovyls/util/GroovyLSUtils.java
This pr adds handy inline icons for some of object mappers when editing in vsc with grs extension.
However there is a few limitations:
- only works on client due to dependency on lwjgl
- does not take into account subsequent mutations on object mapper result e.g nbt
- only works with constant values like `item('minecraft:stone')`
- only shows first matched value e.g ore dictionary
- does not work if mod is not installed (obviously)
- won't work with other language clients without modifications to them e.g nvim (feature is implemented through custom capability)
- won't work for all object mappers by default (requires to implement mapper specific texture binder)
- won't update rendered texture if it changes ahead of cached state
adds a new api to allow future extension of list of supported …
=> Inline icons for Object mappers in vsc

dependencies.gradle, gradle.properties
- since Advanced Rocketry 2 restricts downloads for third parties (a recent change), we cant have it as a dependency. gootbye
=> cant download, wont use

src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Apothecary.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Brew.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/ElvenTrade.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Lexicon.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/ManaInfusion.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/PureDaisy.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/RuneAltar.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Centrifuge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Moistener.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Still.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/recipe/GasRecipeBuilder.java
- since `validate[x](msg)` calls `validate[x](msg, 0, 0, 0, 0)` there is no reason to explicitly use the latter. converted those references to the former in a handful of places.
- fixes `validateGases(msg)` calling `validateItems(msg, 0, 0, 0, 0)` instead of `validateGases(msg, 0, 0, 0, 0)`. shouldnt impact anything, since `validateGases(msg)` isnt used in the main mod currently.
- makes `validateGases` call `validateCustom` for input and output to unify the method used.
=> fix odd validate calls

src/main/java/com/cleanroommc/groovyscript/compat/mods/mekanism/Mekanism.java
- when converting the Mekanism Infusion Type to the GroovyScript Object Mapper version for information reasons, it uses `unlocalizedName` instead of `name`. this makes it incorrect, it is stored based on the name of the Infusion Type.
=> fix infusion type info handler being incorrect

src/main/java/com/cleanroommc/groovyscript/command/BaseInfoCommand.java, src/main/java/com/cleanroommc/groovyscript/command/GSCommand.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/advancedrocketry/BaseRegistry.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/astralsorcery/LightTransmutation.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/Knowledge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/enderio/recipe/CustomEnchanterRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/enderio/recipe/RecipeInput.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/BeeMutations.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/ArcFurnace.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/BlastFurnace.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Fermenter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/immersiveengineering/Squeezer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/rustic/CondenserRecipe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/tinkersconstruct/material/ToolMaterialBuilder.java, src/main/java/com/cleanroommc/groovyscript/core/GroovyScriptCore.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/thermalexpansion/CentrifugeRecipeAccessor.java, src/main/java/com/cleanroommc/groovyscript/registry/DummyRecipe.java
- convert the locations in which `javax.annotation.Nullable` or `javax.annotation.Nonnull` are used instead of `org.jetbrains.annotations.Nullable` or `org.jetbrains.annotations.NotNull` to be the jetbrains version.
=> Convert a handful of javax annotations to jetbrains

src/main/java/com/cleanroommc/groovyscript/compat/mods/appliedenergistics2/AppliedEnergistics2.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thermalexpansion/ThermalExpansion.java, src/main/java/com/cleanroommc/groovyscript/mapper/ObjectMapperManager.java
- add more default values to Object Mappers, specifically Thermal Expansion `compactorMode`, Applied Energistics 2 `tunnel`, and Vanilla `block`, `blockstate`, `creativeTab`, `textformat`, and `nbt`.
- convert Thermal Expansion `compactorMode` Object Mapper to use the `GroovyContainer<?>` argument passed in, as all other mods do.
=> More defaultValues for Object Mappers

examples/postInit/astralsorcery.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/astralsorcery/LightTransmutation.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/astralsorcery/TileCelestialCrystalsMixin.java, src/main/resources/assets/groovyscript/lang/en_us.lang, src/main/resources/mixin.groovyscript.astralsorcery.json
- adds the ability to configure what IBlockState Starmetal Ore converts into while beneath a Celestial Crystal Cluster. adds an example and an i18n key for it.
- this feature requires a mixin, and it uses a `WrapOperation` of the specific IBlockState
=> Astral Sorcery Starmetal Conversion

src/main/java/com/cleanroommc/groovyscript/event/EventHandler.java
- check that the inventory is an instanceof `InventoryCraftResult` before casting to it.
this resolves https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6310
=> Fix EnderIO Inventory Panel Crafting Crash

dependencies.gradle, examples/postInit/silentgems.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/silentsgems/ChaosAltar.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/silentsgems/SilentGems.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- adds compat with Silent's Gems `chaosAltar`. examples and i18n for that.
- does **_not_** add anything else for any other feature of Silent's Gems.
=> add Silent's Gems compat

examples/postInit/custom/vanilla.groovy, src/main/java/com/cleanroommc/groovyscript/command/GSCommand.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/GameRule.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/VanillaModule.java, src/main/java/com/cleanroommc/groovyscript/event/EventHandler.java, src/main/java/com/cleanroommc/groovyscript/sandbox/SandboxData.java
- add the ability to set the default GameRules. can be done one-by-one or en-mass. 
- when a gamerule that doesnt exist tries to be added, log a warning unless the user has run `gameRule.setWarnNewGameRule(false)`.
- add a command `/gs applyDefaultGameRules` to apply these in-game.
- add examples for this
- the default gamerules are applied when `WorldEvent.CreateSpawnPosition` is fired - as far as i can tell, it is only fired once, when the world is created. other places that do similar things listen to `FMLServerStartingEvent` (applies on every load), `WorldEvent.Load` (applies on every load), and a particularly daring one did `EntityJoinWorldEvent`. 
- i tested `WorldEvent.CreateSpawnPosition` on both client and server, and it only runs if the `level.dat` does not …
=> add Default GameRules

dependencies.gradle, examples/postInit/arcaneworld.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/arcaneworld/ArcaneWorld.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/arcaneworld/RitualWrapper.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- add compat with Arcane World `ritual`. examples and i18n for that.
- add a `TODO` in regards to improving the docgen for it, as the current wiki is quite verbose and repetitive. happens in a few other places - mainly the Astral Sorcery Table and Inspirations Cauldron, with maybe some Integrated Dynamics stuff. its not urgent and everything is still documented, its just documented multiple times.
RotN has a [fork](https://www.curseforge.com/minecraft/mc-mods/arcane-world-rotn-edition) of Arcane World, but it changes the signature of the `REGISTRY` field from `IForgeRegistry<Ritual>` to `IForgeRegistryModifiable<Ritual>` and so is not compatible. unsure on how this should be resolved - switching to only supporting RotN?
=> add Arcane World compat

src/main/java/com/cleanroommc/groovyscript/core/mixin/jei/JeiStarterMixin.java
- for adding methods post-jei-op, instead of injecting prior to the last method, inject at the tail.
- it used to be that `ProgressManager.pop` was always the last line, but is changed in [HEI](https://github.com/CleanroomMC/HadEnoughItems/commit/e888878b95aaadcf80f23aaca7ca0a4982f9aef0) and made configurable.
=> Fix HEI config breaking JEI compat

examples/postInit/botania_tweaks.groovy, examples/postInit/quarryplus.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/additionalenchantedminer/AdditionalEnchantedMiner.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/additionalenchantedminer/WorkbenchPlus.java, src/main/java/com/cleanroommc/groovyscript/documentation/Registry.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- fix quarryplus (AdditionalEnchantedMiner) missing a lang key and not being properly formatted.
- update `botania_tweaks.groovy` with the "latest" examples (i think this is actually pre-1.2.0).
- strip the closing period `.` in situations where the line would be immediately followed by a `:` (ie `Cool method.:`)
=> Minor fixes for documentation

src/main/java/com/cleanroommc/groovyscript/GroovyScript.java, src/main/java/com/cleanroommc/groovyscript/IncompatibleJavaException.java, src/main/java/com/cleanroommc/groovyscript/JavaVersionCheck.java, src/main/java/com/cleanroommc/groovyscript/mapper/TextureBinder.java
- extract java version checking to its own class to declutter the GroovyScript class.
- add some javadocs explaining it.
- annotate `TextureBinder.drawSprite` as client-only and return empty functional interfaces so the method isnt called.
- separate the reference to the client-only class `IncompatibleJavaException` into its own method.
resolves #292
=> Fix GroovyScript crashing on servers

src/main/java/com/cleanroommc/groovyscript/GroovyScript.java
- GroovyScript is not compatible with Extended Crafting, and is only compatible with Extended Crafting: Nomifactory Edition. this updated the `@Mod#dependencies` with `after:extendedcrafting@[1.6.0,);` to ensure this is followed.
- `1.5.6` is the last version of extended crafting, and `1.6.0` is the first version of the nomi fork.
reasoning:
- the mixin `ItemRecipeMakerMixin` is written for Nomi, and the Compression Crafting compat errors outside of the Nomi version.
- this is because base extended crafting has a return value of `ArrayList` for `getRecipes`, while nomi fork returns a `List`. this could be fixed via reflection.
test via adding this to `dependencies.gradle`:
```
runtimeOnly(rfg.deobf('curse.maven:cucumber-272335:2645867')) …
```
=> Require Extended Crafting: Nomi Edition

src/main/java/com/cleanroommc/groovyscript/compat/mods/thaumcraft/arcane/ArcaneRecipeBuilder.java
- add multi-value aspect input to `ArcaneRecipeBuilder`. now `.aspect(aspect('ignis'), aspect('aqua'))` works, instead of requiring up to 6 separate calls.
=> Arcane Recipe Builder aspect call enhancement

examples/postInit/custom/hard_mode.groovy, examples/postInit/custom/normal_mode.gvy, examples/postInit/custom/reloading_compat.groovy, examples/preInit/vanilla.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/BlastFurnace.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/Campfire.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/Smoker.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/Stonecutter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/horsepower/ChoppingBlock.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/horsepower/ManualChoppingBlock.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/randomthings/Anvil.java
- add `getMaxItemInput` 1 to some places missing it - currently only registries from `futuremc`, `horsepower`, `randomthings`.
- fix leftover `placeholdername:` in comments and some example files, which caused errors.
- convert the reloading example from event-based (which doesnt work) to `isReloading()`.
=> Adjust getMaxItemInput in missing places, fix examples 

src/main/java/com/cleanroommc/groovyscript/api/infocommand/InfoParser.java, src/main/java/com/cleanroommc/groovyscript/api/infocommand/InfoParserRegistry.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/InfoParserTab.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/command/infoparser/InfoParserItem.java
- fix formatting characters being copied to hand.
- move client-only copying to only run on the client.
- only run the jei tab parser if its clientside (avoid crashing).
- add comments to `InfoParserRegistry` and adjust some logic to not make streams constantly.
=> Fix info command copying formatting

dependencies.gradle, examples/postInit/factorytech.groovy, gradle.properties, src/main/java/com/cleanroommc/groovyscript/compat/mods/ModSupport.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Agitator.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Centrifuge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/CircuitScribe.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Compressor.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Crucible.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/DeepDrill.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Disassembler.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Electroplater.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/FactoryTech.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Grindstone.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/HighTechFurnace.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/MagnetCentrifuge.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Magnetizer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/MetalCutter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/OreDrill.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Reclaimer.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Refrigerator.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/RiverGrate.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Saw.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/factorytech/Temperer.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- add compat with Factory Tech `agitator`, `centrifuge`, `circuitScribe`, `compressor`, `crucible`, `deepDrill`, `disassembler`, `electroplater`, `grindstone`, `highTechFurnace`, `magnetCentrifuge`, `magnetizer`, `metalCutter`, `oreDrill`, `reclaimer`, `refrigerator`, `riverGrate`, `saw`, and `temperer`. examples and i18n for those.
- apply the `getMaxItemInput` method to all applicable.
=> add Factory Tech compat

examples/postInit/thebetweenlands.groovy, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/command/infoparser/InfoParserItem.java
- fix formatting characters being copied when running an info parser
- ran docgen and it added a line of whitespace to `thebetweenlands.groovy`
didnt do things correctly in #305
=> Fix GS Info Item Copying Formatting Characters

examples/assets/groovyscriptdev/lang/en_us.lang, examples/assets/groovyscriptdev/models/item/debug_stick.json, examples/preInit/DebugTool.groovy
- add the debug stick with comments about the code as an example of high-end custom content.
- the model points to the `minecraft:stick` resource location, so no new texture.
=> Debug Stick example script

examples/postInit/futuremc.groovy, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/Composter.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/futuremc/FutureMC.java, src/main/resources/assets/groovyscript/lang/en_us.lang
- add compat with the FutureMC Composter. it was rather miserable.
followup to #254
=> add FutureMC Composter compat

src/main/java/com/cleanroommc/groovyscript/compat/mods/thaumcraft/Crucible.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thaumcraft/InfusionCrafting.java
- fix thaumcraft `InfusionCrafting` ignoring the `name` field and always generating a random RL. this prevents using a specific RL for the recipe, which is required to add it to the thaumonomicon.
- add docgen annotations for `InfusionCrafting` and `Crucible` for missing fields.
=> Infusion Crafting name usage

src/main/java/com/cleanroommc/groovyscript/event/EventHandler.java
- split login event to have inventory logic be on `EventPriority.LOWEST` to allow clearing the inventory to work correctly
=> Fix Player Inventory Priority

src/main/java/com/cleanroommc/groovyscript/sandbox/CustomGroovyScriptEngine.java
- check if cache exists before cleaning. 
if delete cache on run is enabled, it will attempt to delete everything in the cache. if the cache is always disabled, the folder will never be created. if both are true, this will cause an `IllegalArgumentException`.
=> Fix constant crash when cache always disabled

src/main/java/com/cleanroommc/groovyscript/GroovyScript.java, src/main/java/com/cleanroommc/groovyscript/command/GSCommand.java, src/main/java/com/cleanroommc/groovyscript/compat/content/GroovyBlock.java, src/main/java/com/cleanroommc/groovyscript/compat/content/GroovyItem.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/Burning.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/Explosion.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/FluidToBlock.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/FluidToFluid.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/FluidToItem.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/PistonPush.java, src/main/java/com/cleanroommc/groovyscript/compat/inworldcrafting/jei/InWorldCraftingJeiPlugin.java, src/main/java/com/cleanroommc/groovyscript/compat/loot/LootEntryBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/loot/LootPoolBuilder.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/jei/Ingredient.java, src/main/java/com/cleanroommc/groovyscript/compat/mods/thaumcraft/arcane/ArcaneWorkbench.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/Furnace.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/ItemStackExpansion.java, src/main/java/com/cleanroommc/groovyscript/compat/vanilla/VanillaModule.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/EntityItemMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/ItemMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/TileEntityPistonMixin.java, src/main/java/com/cleanroommc/groovyscript/core/mixin/loot/LoadTableEventMixin.java, src/main/java/com/cleanroommc/groovyscript/event/EventHandler.java, src/main/java/com/cleanroommc/groovyscript/event/LootTablesLoadedEvent.java, src/main/java/com/cleanroommc/groovyscript/helper/ingredient/OreDictIngredient.java, src/main/java/com/cleanroommc/groovyscript/registry/AbstractCraftingRecipeBuilder.java
- make the currently `static` property fields of `VanillaModule` non-static.
- convert the properties added as global bindings to a list.
- remove some global bindings - specifically `player`, `loot`, `rarity`, `command`, and `gameRule`. 
- create a way to add additional properties to the `VanillaModule`, include a shorthand way to make it a global binding (relevant for mods that add functionality involving vanilla features).
=> Improve VanillaModule design
